# Generated by Django 5.2.14 on 2026-05-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='dynamic_pricing_enabled',
            field=models.BooleanField(default=False, help_text='Toggle Dynamic Pricing system'),
        ),
        migrations.AddField(
            model_name='business',
            name='expiry_alert_days',
            field=models.IntegerField(default=30, help_text='Days prior to expiry for warning alerts'),
        ),
        migrations.AddField(
            model_name='business',
            name='forecasting_enabled',
            field=models.BooleanField(default=True, help_text='Toggle Demand Forecasting module'),
        ),
        migrations.AddField(
            model_name='business',
            name='low_stock_threshold',
            field=models.IntegerField(default=5, help_text='Minimum stock level for alerts'),
        ),
        migrations.AddField(
            model_name='business',
            name='pricing_clearance_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Percent price discount for near-expiry clearance', max_digits=5),
        ),
        migrations.AddField(
            model_name='business',
            name='pricing_high_demand_percent',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Percent price increase for high demand', max_digits=5),
        ),
        migrations.AddField(
            model_name='business',
            name='pricing_low_stock_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percent price increase for low stock', max_digits=5),
        ),
        migrations.AddField(
            model_name='business',
            name='smart_insights_enabled',
            field=models.BooleanField(default=True, help_text='Toggle Smart Insights module'),
        ),
    ]
