# Generated by Django 5.2.14 on 2026-05-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_business_dynamic_pricing_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='batch_tracking_enabled',
            field=models.BooleanField(default=True, help_text='Toggle Batch & Expiry tracking module'),
        ),
    ]
