# Generated by Django 5.2.14 on 2026-06-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_plan_business_subscription_plan_subscriptionpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='price',
            new_name='price_3_months',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='plan',
            name='price_6_months',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_year',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='duration_months',
            field=models.IntegerField(default=3, help_text='Duration purchased in months'),
        ),
    ]
