# Generated by Django 5.2.14 on 2026-06-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_price_plan_price_3_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='upi_utr_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
