# Generated by Django 5.2.14 on 2026-06-19 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_subscriptionpayment_upi_utr_number'),
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_key', models.CharField(db_index=True, max_length=200)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_alerts', to='core.business')),
            ],
            options={
                'unique_together': {('business', 'alert_key')},
            },
        ),
    ]
