# Generated by Django 5.2.14 on 2026-08-08 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_demorequest'),
        ('intelligence', '0002_dismissedalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dismissedalert',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_alerts', to='core.business'),
        ),
    ]
