"""
Django settings for retail_billing project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1&&tl7@(!ja(+i&_5%(e4f4hyft36&47xppif+!6tff3yxj18b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    'https://*.loca.lt',
    'https://*.ngrok.io',
    'https://*.lhr.life',
    'https://*.trycloudflare.com',
    'https://*.onrender.com',
    'https://*.web.app',
    'https://*.firebaseapp.com'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'inventory',
    'billing',
    'intelligence',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.BusinessStatusMiddleware',
]

ROOT_URLCONF = 'retail_billing.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'retail_billing.wsgi.application'


# Database Configuration (MySQL / TiDB)
import os

DATABASE_URL = os.environ.get('DATABASE_URL')
DB_NAME = os.environ.get('DB_NAME')
DB_USER = os.environ.get('DB_USER')
DB_PASSWORD = os.environ.get('DB_PASSWORD')
DB_HOST = os.environ.get('DB_HOST')
DB_PORT = os.environ.get('DB_PORT', '3306')
DB_SSL_CA = os.environ.get('DB_SSL_CA')

# If DB_SSL_CA is not set, check local path or standard Linux system paths
if not DB_SSL_CA:
    local_ca = os.path.join(BASE_DIR, 'ca.pem')
    if os.path.exists(local_ca):
        DB_SSL_CA = local_ca
    else:
        # Standard system CA bundle paths on various Linux distributions (like Render's environment)
        linux_ca_paths = [
            '/etc/ssl/certs/ca-certificates.crt',                  # Debian/Ubuntu/Render
            '/etc/pki/tls/certs/ca-bundle.crt',                    # Fedora/RHEL 6
            '/etc/ssl/ca-bundle.pem',                              # OpenSUSE
            '/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem',    # CentOS/RHEL 7/8
        ]
        for path in linux_ca_paths:
            if os.path.exists(path):
                DB_SSL_CA = path
                break

db_configured = False

# 1. Parse MySQL / TiDB DATABASE_URL
if DATABASE_URL and (DATABASE_URL.startswith('mysql://') or DATABASE_URL.startswith('mysql+ssl://')):
    try:
        url = DATABASE_URL
        if url.startswith('mysql+ssl://'):
            url = url[len('mysql+ssl://'):]
        else:
            url = url[len('mysql://'):]
            
        if '@' in url:
            credentials, location = url.split('@', 1)
            user, password = credentials.split(':', 1)
            if '/' in location:
                host_port, db_name = location.split('/', 1)
                if '?' in db_name:
                    db_name = db_name.split('?', 1)[0]
                if ':' in host_port:
                    host, port = host_port.split(':', 1)
                else:
                    host = host_port
                    port = '3306'
                
                options = {
                    'charset': 'utf8mb4',
                    'use_unicode': True,
                }
                if DB_SSL_CA:
                    options['ssl'] = {'ca': DB_SSL_CA}
                    
                DATABASES = {
                    'default': {
                        'ENGINE': 'django.db.backends.mysql',
                        'NAME': db_name,
                        'USER': user,
                        'PASSWORD': password,
                        'HOST': host,
                        'PORT': port,
                        'OPTIONS': options
                    }
                }
                db_configured = True
                print("[Database] Using production/cloud MySQL/TiDB database parsed from DATABASE_URL.")
    except Exception as e:
        print(f"[Database Error] Failed to parse MySQL/TiDB DATABASE_URL: {str(e)}")

# 2. Default Fallback Configuration (MySQL / TiDB)
if not db_configured:
    options = {
        'charset': 'utf8mb4',
        'use_unicode': True,
    }
    if DB_SSL_CA:
        options['ssl'] = {'ca': DB_SSL_CA}
        
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': DB_NAME if DB_NAME else 'test',
            'USER': DB_USER if DB_USER else '2hi2kChfmfuNZXu.root',
            'PASSWORD': DB_PASSWORD if DB_PASSWORD else 'H1wlE5nMhhWM4Qab',
            'HOST': DB_HOST if DB_HOST else 'gateway01.ap-southeast-1.prod.aws.tidbcloud.com',
            'PORT': DB_PORT if DB_PORT else '4000',
            'OPTIONS': options
        }
    }
    print("[Database] Configured for MySQL/TiDB.")



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_ROOT = BASE_DIR / 'public' / 'static'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/dashboard/'
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Email Configurations
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'billing@zenelait.com' # Replace with your actual email
EMAIL_HOST_PASSWORD = '' # Replace with your App Password
DEFAULT_FROM_EMAIL = 'billing@zenelait.com'

# Razorpay Configurations
RAZORPAY_KEY_ID = 'rzp_test_SwFutc3AGUQkSR'
RAZORPAY_KEY_SECRET = 'tN2QsZzR7oVZTOXKQWIE5Z8T'

# UPI ID Configuration for Dynamic QR Payments
UPI_ID = '9884264816@ybl'


