# Generated by Django 5.2.14 on 2026-05-18 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_business_dynamic_pricing_enabled_and_more'),
        ('inventory', '0006_category_business_product_business_purchase_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('stock_quantity', models.IntegerField(default=0)),
                ('initial_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='inventory.batch'),
        ),
    ]
